# Employment Dataset Pre-processing (UK Gender Pay Gap)

Dropping columns that we don't use in our experiments.

## Imports

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/raw/uk_gender_pay_gap_data_2024_to_2025.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11239 entries, 0 to 11238
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   EmployerName               11239 non-null  object
 1   EmployerId                 11239 non-null  int64
 2   Address                    11205 non-null  object
 3   PostCode                   11181 non-null  object
 4   CompanyNumber              9756 non-null   object
 5   SicCodes                   10329 non-null  object
 6   DiffMeanHourlyPercent      11239 non-null  float64
 7   DiffMedianHourlyPercent    11239 non-null  float64
 8   DiffMeanBonusPercent       8520 non-null   float64
 9   DiffMedianBonusPercent     8520 non-null   float64
 10  MaleBonusPercent           11239 non-null  float64
 11  FemaleBonusPercent         11239 non-null  float64
 12  MaleLowerQuartile          11239 non-null  float64
 13  FemaleLowerQuartile        11239 non-null  float64
 14  MaleLowerMiddleQuartile    11239 non-null  float64
 15  FemaleLowerMiddleQuartile  11239 non-null  float64
 16  MaleUpperMiddleQuartile    11239 non-null  float64
 17  FemaleUpperMiddleQuartile  11239 non-null  float64
 18  MaleTopQuartile            11239 non-null  float64
 19  FemaleTopQuartile          11239 non-null  float64
 20  CompanyLinkToGPGInfo       6057 non-null   object
 21  ResponsiblePerson          9302 non-null   object
 22  EmployerSize               11239 non-null  object
 23  CurrentName                11239 non-null  object
 24  SubmittedAfterTheDeadline  11239 non-null  bool
 25  DueDate                    11239 non-null  object
 26  DateSubmitted              11239 non-null  object
dtypes: bool(1), float64(14), int64(1), object(11)
memory usage: 2.2+ MB

In [4]:
df.shape

(11239, 27)

In [5]:
df.describe

<bound method NDFrame.describe of                                             EmployerName  EmployerId  \
0      'PRIFYSGOL ABERYSTWYTH' AND 'ABERYSTWYTH UNIVE...       19070
1                   "RED BAND" CHEMICAL COMPANY, LIMITED       16879
2                        10 TRINITY SQUARE HOTEL LIMITED       19455
3                                           10442565 LTD       19491
4                                             1509 GROUP       15320
...                                                  ...         ...
11234                                    ZSCALER UK LTD.       22454
11235                 ZURICH EMPLOYMENT SERVICES LIMITED       14076
11236                 ZURICH UK GENERAL SERVICES LIMITED       14078
11237                                       ZUTO LIMITED       14080
11238                   ZWANENBERG FOOD GROUP UK LIMITED       14081

                                                 Address  PostCode  \
0      Aberystwyth University, Penglais, Ceredigion, ...  SY23 3FL
1       19 Smith's Place, Leith Walk, Edinburgh, EH6 8NU   EH6 8NU
2      5 Market Yard Mews, 194-204 Bermondsey Street,...   SE1 3TQ
3      Compass House 17-19 Empringham Street, Kingsto...   HU9 1RP
4      Royal Grammar School, High Street, Guildford, ...   GU1 3BB
...                                                  ...       ...
11234  C/O Csc Cls (Uk) Limited 5 Churchill Place, 10...   E14 5HU
11235  Unity Place, 1 Carfax Close, Swindon, Wiltshir...   SN1 1AP
11236  The Zurich Centre 3000 Parkway, Whiteley, Fare...  PO15 7JZ
11237  Winterton House, Winterton Way, Macclesfield, ...  SK11 0LP
11238  Station Road, Minsterley, Shrewsbury, Shropshi...   SY5 0BD

      CompanyNumber       SicCodes  DiffMeanHourlyPercent  \
0          RC000641            NaN                   9.17
1          SC016876          47730                   8.75
2          08064685          82990                  -2.20
3          10442565          70229                  11.00
4          04104101  85200,\n85310                  20.12
...             ...            ...                    ...
11234      10299928          62090                  36.40
11235      00243883  78300,\n82990                  27.10
11236      03843124          82990                  13.80
11237      05722976          64999                  20.20
11238      01032611  10110,\n10130                  18.60

       DiffMedianHourlyPercent  DiffMeanBonusPercent  DiffMedianBonusPercent  \
0                         2.90                  7.50                    0.00
1                        -4.96                 20.83                   36.88
2                         8.40                -93.90                    0.00
3                         3.60                 26.10                    4.90
4                        17.48                   NaN                     NaN
...                        ...                   ...                     ...
11234                    16.30                 37.40                   25.40
11235                    27.60                 58.60                   43.40
11236                    12.60                 35.90                   21.30
11237                    12.30                 11.30                   23.80
11238                     3.20                 90.00                    0.00

       ...  FemaleUpperMiddleQuartile  MaleTopQuartile  FemaleTopQuartile  \
0      ...                      60.33            53.62              46.38
1      ...                      89.50            26.10              73.90
2      ...                      34.00            63.00              37.00
3      ...                      33.20            60.00              40.00
4      ...                      52.94            73.53              26.47
...    ...                        ...              ...                ...
11234  ...                      24.00            86.00              14.00
11235  ...                      51.50            62.20              37.80
11236  ...                      35.60            64.10              35.90
11237  ...                      21.70            72.80              27.20
11238  ...                      44.10            69.70              30.30

                                    CompanyLinkToGPGInfo  \
0      https://www.aber.ac.uk/en/equality/equality-re...
1                                                    NaN
2               https://www.fourseasons.com/towerbridge/
3                                                    NaN
4                                  http://www.rgsg.co.uk
...                                                  ...
11234                                                NaN
11235  https://www.zurich.co.uk/about-us/diversity-an...
11236  https://www.zurich.co.uk/about-us/diversity-an...
11237        https://www.zuto.com/gender-pay-report/2025
11238                                                NaN

                                    ResponsiblePerson  EmployerSize  \
0                      Dylan Jones (dej20@aber.ac.uk)  1000 to 4999
1                   Osmond Ramsay (Managing Director)    250 to 499
2      Linda Stigter (Director of People and Culture)    250 to 499
3                         David Maccormack (Director)  1000 to 4999
4                         Catherine Perceval (Bursar)    250 to 499
...                                               ...           ...
11234           Brendan Castle (Chief People Officer)    250 to 499
11235           Steve Collinson (Head of People Team)  1000 to 4999
11236           Steve Collinson (Head of People Team)  1000 to 4999
11237     Mary Beighton (People and Culture Director)    250 to 499
11238                          Jonathan Ashmore (CEO)    500 to 999

                                             CurrentName  \
0      'PRIFYSGOL ABERYSTWYTH' AND 'ABERYSTWYTH UNIVE...
1                   "RED BAND" CHEMICAL COMPANY, LIMITED
2                        10 TRINITY SQUARE HOTEL LIMITED
3                                           10442565 LTD
4                                             1509 GROUP
...                                                  ...
11234                                    ZSCALER UK LTD.
11235                 ZURICH EMPLOYMENT SERVICES LIMITED
11236                 ZURICH UK GENERAL SERVICES LIMITED
11237                                       ZUTO LIMITED
11238                   ZWANENBERG FOOD GROUP UK LIMITED

       SubmittedAfterTheDeadline              DueDate        DateSubmitted
0                          False  2025/04/05 00:00:00  2025/03/28 09:02:53
1                           True  2025/04/05 00:00:00  2025/04/11 07:57:32
2                          False  2025/04/05 00:00:00  2025/01/21 14:19:52
3                          False  2025/04/05 00:00:00  2025/04/03 12:14:38
4                          False  2025/04/05 00:00:00  2025/03/28 11:23:54
...                          ...                  ...                  ...
11234                      False  2025/04/05 00:00:00  2025/04/04 09:13:07
11235                      False  2025/04/05 00:00:00  2024/10/16 08:51:47
11236                      False  2025/04/05 00:00:00  2024/10/16 08:55:41
11237                      False  2025/04/05 00:00:00  2025/04/01 10:18:03
11238                      False  2025/04/05 00:00:00  2025/04/03 07:53:16

[11239 rows x 27 columns]>

In [6]:
df.head()

,EmployerName,EmployerId,Address,PostCode,CompanyNumber,SicCodes,DiffMeanHourlyPercent,DiffMedianHourlyPercent,DiffMeanBonusPercent,DiffMedianBonusPercent,...,FemaleUpperMiddleQuartile,MaleTopQuartile,FemaleTopQuartile,CompanyLinkToGPGInfo,ResponsiblePerson,EmployerSize,CurrentName,SubmittedAfterTheDeadline,DueDate,DateSubmitted
0,'PRIFYSGOL ABERYSTWYTH' AND 'ABERYSTWYTH UNIVE...,19070,"Aberystwyth University, Penglais, Ceredigion, ...",SY23 3FL,RC000641,NaN,9.17,2.90,7.50,0.00,...,60.33,53.62,46.38,https://www.aber.ac.uk/en/equality/equality-re...,Dylan Jones (dej20@aber.ac.uk),1000 to 4999,'PRIFYSGOL ABERYSTWYTH' AND 'ABERYSTWYTH UNIVE...,False,2025/04/05 00:00:00,2025/03/28 09:02:53
1,"""RED BAND"" CHEMICAL COMPANY, LIMITED",16879,"19 Smith's Place, Leith Walk, Edinburgh, EH6 8NU",EH6 8NU,SC016876,47730,8.75,-4.96,20.83,36.88,...,89.50,26.10,73.90,NaN,Osmond Ramsay (Managing Director),250 to 499,"""RED BAND"" CHEMICAL COMPANY, LIMITED",True,2025/04/05 00:00:00,2025/04/11 07:57:32
2,10 TRINITY SQUARE HOTEL LIMITED,19455,"5 Market Yard Mews, 194-204 Bermondsey Street,...",SE1 3TQ,08064685,82990,-2.20,8.40,-93.90,0.00,...,34.00,63.00,37.00,https://www.fourseasons.com/towerbridge/,Linda Stigter (Director of People and Culture),250 to 499,10 TRINITY SQUARE HOTEL LIMITED,False,2025/04/05 00:00:00,2025/01/21 14:19:52
3,10442565 LTD,19491,"Compass House 17-19 Empringham Street, Kingsto...",HU9 1RP,10442565,70229,11.00,3.60,26.10,4.90,...,33.20,60.00,40.00,NaN,David Maccormack (Director),1000 to 4999,10442565 LTD,False,2025/04/05 00:00:00,2025/04/03 12:14:38
4,1509 GROUP,15320,"Royal Grammar School, High Street, Guildford, ...",GU1 3BB,04104101,"85200,\n85310",20.12,17.48,NaN,NaN,...,52.94,73.53,26.47,http://www.rgsg.co.uk,Catherine Perceval (Bursar),250 to 499,1509 GROUP,False,2025/04/05 00:00:00,2025/03/28 11:23:54

In [7]:
df.isnull().sum()

EmployerName                    0
EmployerId                      0
Address                        34
PostCode                       58
CompanyNumber                1483
SicCodes                      910
DiffMeanHourlyPercent           0
DiffMedianHourlyPercent         0
DiffMeanBonusPercent         2719
DiffMedianBonusPercent       2719
MaleBonusPercent                0
FemaleBonusPercent              0
MaleLowerQuartile               0
FemaleLowerQuartile             0
MaleLowerMiddleQuartile         0
FemaleLowerMiddleQuartile       0
MaleUpperMiddleQuartile         0
FemaleUpperMiddleQuartile       0
MaleTopQuartile                 0
FemaleTopQuartile               0
CompanyLinkToGPGInfo         5182
ResponsiblePerson            1937
EmployerSize                    0
CurrentName                     0
SubmittedAfterTheDeadline       0
DueDate                         0
DateSubmitted                   0
dtype: int64

In [8]:
drop_cols = [
    "EmployerId", "Address", "PostCode", "CompanyNumber", 
    "CompanyLinkToGPGInfo", "ResponsiblePerson", "CurrentName", 
    "SubmittedAfterTheDeadline", "DueDate"
]

In [9]:
df = df.drop(columns=drop_cols, errors="ignore")

In [10]:
percent_cols = [
    "DiffMeanHourlyPercent", "DiffMedianHourlyPercent",
    "DiffMeanBonusPercent", "DiffMedianBonusPercent",
    "MaleBonusPercent", "FemaleBonusPercent",
    "MaleLowerQuartile", "FemaleLowerQuartile",
    "MaleLowerMiddleQuartile", "FemaleLowerMiddleQuartile",
    "MaleUpperMiddleQuartile", "FemaleUpperMiddleQuartile",
    "MaleTopQuartile", "FemaleTopQuartile"
]

df[percent_cols] = df[percent_cols].apply(pd.to_numeric, errors="coerce")

In [11]:
df = df.replace(["", "NULL", "NaN", "NA"], pd.NA)

In [12]:
df["EmployerSize"] = df["EmployerSize"].str.replace(" to ", "-", regex=False)

In [13]:
df["DateSubmitted"] = pd.to_datetime(df["DateSubmitted"], errors="coerce")

In [14]:
df.to_csv("../../data/preprocessed/uk_gender_pay_gap_data_2024_to_2025_preproccesed.csv", index=False)

In [15]:
df_preprocessed = pd.read_csv("../../data/preprocessed/uk_gender_pay_gap_data_2024_to_2025_preproccesed.csv")

In [16]:
df_preprocessed

,EmployerName,SicCodes,DiffMeanHourlyPercent,DiffMedianHourlyPercent,DiffMeanBonusPercent,DiffMedianBonusPercent,MaleBonusPercent,FemaleBonusPercent,MaleLowerQuartile,FemaleLowerQuartile,MaleLowerMiddleQuartile,FemaleLowerMiddleQuartile,MaleUpperMiddleQuartile,FemaleUpperMiddleQuartile,MaleTopQuartile,FemaleTopQuartile,EmployerSize,DateSubmitted
0,'PRIFYSGOL ABERYSTWYTH' AND 'ABERYSTWYTH UNIVE...,NaN,9.17,2.90,7.50,0.00,6.0,3.3,47.73,52.27,40.17,59.83,39.67,60.33,53.62,46.38,1000-4999,2025-03-28 09:02:53
1,"""RED BAND"" CHEMICAL COMPANY, LIMITED",47730,8.75,-4.96,20.83,36.88,24.6,75.4,56.20,43.80,23.90,76.10,10.50,89.50,26.10,73.90,250-499,2025-04-11 07:57:32
2,10 TRINITY SQUARE HOTEL LIMITED,82990,-2.20,8.40,-93.90,0.00,39.2,58.6,66.00,34.00,46.00,54.00,66.00,34.00,63.00,37.00,250-499,2025-01-21 14:19:52
3,10442565 LTD,70229,11.00,3.60,26.10,4.90,3.0,2.0,76.30,23.70,69.60,30.40,66.80,33.20,60.00,40.00,1000-4999,2025-04-03 12:14:38
4,1509 GROUP,"85200,\n85310",20.12,17.48,NaN,NaN,0.0,0.0,30.43,69.57,39.71,60.29,47.06,52.94,73.53,26.47,250-499,2025-03-28 11:23:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11234,ZSCALER UK LTD.,62090,36.40,16.30,37.40,25.40,92.7,91.6,61.00,39.00,64.00,36.00,76.00,24.00,86.00,14.00,250-499,2025-04-04 09:13:07
11235,ZURICH EMPLOYMENT SERVICES LIMITED,"78300,\n82990",27.10,27.60,58.60,43.40,96.5,94.9,32.00,68.00,37.20,62.80,48.50,51.50,62.20,37.80,1000-4999,2024-10-16 08:51:47
11236,ZURICH UK GENERAL SERVICES LIMITED,82990,13.80,12.60,35.90,21.30,94.2,95.5,44.60,55.40,60.90,39.10,64.40,35.60,64.10,35.90,1000-4999,2024-10-16 08:55:41
11237,ZUTO LIMITED,64999,20.20,12.30,11.30,23.80,78.6,77.6,64.70,35.30,56.50,43.50,78.30,21.70,72.80,27.20,250-499,2025-04-01 10:18:03
11238,ZWANENBERG FOOD GROUP UK LIMITED,"10110,\n10130",18.60,3.20,90.00,0.00,65.3,68.8,37.90,62.10,62.10,37.90,55.90,44.10,69.70,30.30,500-999,2025-04-03 07:53:16